### ISSUE TITLE
Name conflict with mdgriffith/elm-markup

### ISSUE THREAD

**Issue by albertdahlin** [ChristophP/elm-mark#3]
Thank you for a nice and well documented package.

[mdgriffith/elm-markup](https://github.com/mdgriffith/elm-markup) also exposes a `Mark` module which means you can't use these two packages in the same project.

Right now there is no way of solving these kinds of conflicts in directly in Elm or the compiler so I'd have to fork one package just to rename the module.

Personally I like to add a vender prefix for modules I publish to avoid these problems, this is also how most other programming languages does it but I know some people hates long namespaces.

**Comment by ChristophP** [comment]
Alright I am contacting the author of elm-markup. Let's see what comes out of that. I'd like to get that resolved so that users won't have to choose.

**Comment by ChristophP** [comment]
I talked to Matt Griffith, the author of `elm-mark`. I decided to go with `String.Mark` as a module name, so that there won't be any delays in removing the name collision.
@albertdahlin Do you think `String.Mark` is okay? There are no collisions yet to my knowledge. Do you any modules that would clash with this?

**Comment by albertdahlin** [comment]
I don't know of any other `String.Mark` module so this should be ok.

**Comment by ChristophP** [comment]
Alright thanks, will publish
